### PR TITLE
docker ps style filtering of containers and slack notifications

### PR DESCRIPTION
**Pull request by ubergesundheit**
Hi,

first off: I have very little experience in writing go, so please point out any errors I made and I will try to fix them.
I am opening this pull request against your repository as it seems you are actively developing your fork and maybe will eventually try to merge everything back to the original repository.

I've built upon your work in your branch [1.12](https://github.com/stffabi/watchtower/tree/1.12) three changes:
- the `--ps-filter` which allows to specify `docker ps` style filters for containers watchtower watches on
- updating and restarting of stopped containers. This is useful for me because I like to use one shot containers with volumes for static html
- a slack webhook notification feature on successful updated containers and errors

Unfortunately after cleaning up my (ps-filter)[https://github.com/ubergesundheit/watchtower/tree/ps-filter] branch and merging with your (master)[https://github.com/stffabi/watchtower/commit/48b8b5976fcb8b78e9acb626b917731580bb256f] branch. I am unable to build the docker image. Here are the logs
```
github.com/Sirupsen/logrus (download)
github.com/mozillazg/request (download)
github.com/bitly/go-simplejson (download)
Fetching https://golang.org/x/net/proxy?go-get=1
Parsing meta tags from https://golang.org/x/net/proxy?go-get=1 (status code 200)
get "golang.org/x/net/proxy": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/proxy?go-get=1
get "golang.org/x/net/proxy": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://golang.org/x/net/publicsuffix?go-get=1
Parsing meta tags from https://golang.org/x/net/publicsuffix?go-get=1 (status code 200)
get "golang.org/x/net/publicsuffix": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/publicsuffix?go-get=1
get "golang.org/x/net/publicsuffix": verifying non-authoritative meta tag
github.com/docker/docker (download)
github.com/docker/engine-api (download)
github.com/docker/distribution (download)
github.com/docker/go-connections (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
github.com/docker/go-units (download)
github.com/urfave/cli (download)
github.com/stretchr/testify (download)
Building github.com/stffabi/watchtower
# github.com/docker/engine-api/client/transport
/go/src/github.com/docker/engine-api/client/transport/tlsconfig_clone.go:10: c.Clone undefined (type *tls.Config has no field or method Clone)
```
I would appreciate to hear from you.

Cheers,
ubergesundheit

### CODE REVIEW

**Comment by stffabi** [comment]
Thanks @ubergesundheit for your contribution. I'm currently in contact with CenturyLink for possibly taking over the maintenance of the original repo.
Please allow me some time to finish this, afterwards we could either abandon this PR for a new one directly on the original repo or we can continue here.

**Comment by ubergesundheit** [comment]
Cool. That would be awesome

**Comment by ubergesundheit** [comment]
Any news?

**Comment by stffabi** [comment]
Yes, I've taken over the maintenance of the main repo, but I'm still working on some refactoring of the build process. It should be finished by the end of the week.
I'll let you know as soon I've finished it and you could proceed with a new PR on the main repo.

**Comment by stffabi** [comment]
@ubergesundheit would it be possible for you to make new PR's on the main repo? Could you also provide 3 PR's for every change? That would be really great. Thanks again for your contribution.

**Pull request closed without merging**
